affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
fullnameOverride: ''

image:
  pullPolicy: Always
  repository: albird/node-red-krones-edition
  tag: latest
imagePullSecrets: []

workercounter: 1

volumeExists: false
skipuninstall: false
persistence:
  claimName: node-red-labeler-claimdata
  volumeName: node-red-labeler-volume
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  storage: 1Gi


ingress:
  host: ""
  annotations: {}
  enabled: true

nodered:
  flow: ""

nameOverride: ''
nodeSelector: {}
podAnnotations: {}
podSecurityContext:
  fsGroup: 2000
ports:
  - containerPort: 1880
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 1880
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: ''
tolerations: []
